export const CREATE_EXPENSE_REQUEST="CREATE_EXPENSE_REQUEST";
export const CREATE_EXPENSE_SUCCESS="CREATE_EXPENSE_SUCCESS";
export const CREATE_EXPENSE_FAIL="CREATE_EXPENSE_FAIL";
export const CREATE_EXPENSE_RESET="CREATE_EXPENSE_RESET";


export const EXPENSE_DETAILS_REQUEST="EXPENSE_DETAILS_REQUEST";
export const EXPENSE_DETAILS_SUCCESS="EXPENSE_DETAILS_SUCCESS";
export const EXPENSE_DETAILS_FAIL="EXPENSE_DETAILS_FAIL";

export const DELETE_EXPENSE_REQUEST="DELETE_EXPENSE_REQUEST";
export const DELETE_EXPENSE_SUCCESS="DELETE_EXPENSE_SUCCESS";
export const DELETE_EXPENSE_FAIL="DELETE_EXPENSE_FAIL";
export const DELETE_EXPENSE_RESET="DELETE_EXPENSE_RESET";

export const CLEAR_ERRORS="CLEAR_ERRORS";