export const CREATE_EXPENSE_REQUEST="CREATE_EXPENSE_REQUEST";
export const CREATE_EXPENSE_SUCCESS="CREATE_EXPENSE_SUCCESS";
export const CREATE_EXPENSE_FAIL="CREATE_EXPENSE_FAIL";
export const CREATE_EXPENSE_RESET="CREATE_EXPENSE_RESET";

export const CLEAR_ERRORS="CLEAR_ERRORS";