export const MY_GROUP_REQUEST="MY_GROUP_REQUEST";
export const MY_GROUP_SUCCESS="MY_GROUP_SUCCESS";
export const MY_GROUP_FAIL="MY_GROUP_FAIL";

export const CREATE_GROUP_REQUEST="CREATE_GROUP_REQUEST";
export const CREATE_GROUP_SUCCESS="CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAIL="CREATE_GROUP_FAIL";
export const CREATE_GROUP_RESET="CREATE_GROUP_RESET";

export const GROUP_DETAILS_REQUEST="GROUP_DETAILS_REQUEST";
export const GROUP_DETAILS_SUCCESS="GROUP_DETAILS_SUCCESS";
export const GROUP_DETAILS_FAIL="GROUP_DETAILS_FAIL";

export const GROUP_BALANCES_REQUEST="GROUP_BALANCES_REQUEST";
export const GROUP_BALANCES_SUCCESS="GROUP_BALANCES_SUCCESS";
export const GROUP_BALANCES_FAIL="GROUP_BALANCES_FAIL";

export const CLEAR_ERRORS="CLEAR_ERRORS";