export const MY_GROUP_REQUEST="MY_GROUP_REQUEST";
export const MY_GROUP_SUCCESS="MY_GROUP_SUCCESS";
export const MY_GROUP_FAIL="MY_GROUP_FAIL";

export const CREATE_GROUP_REQUEST="CREATE_GROUP_REQUEST";
export const CREATE_GROUP_SUCCESS="CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAIL="CREATE_GROUP_FAIL";
export const CREATE_GROUP_RESET="CREATE_GROUP_RESET";

export const GROUP_DETAILS_REQUEST="GROUP_DETAILS_REQUEST";
export const GROUP_DETAILS_SUCCESS="GROUP_DETAILS_SUCCESS";
export const GROUP_DETAILS_FAIL="GROUP_DETAILS_FAIL";

export const GROUP_BALANCES_REQUEST="GROUP_BALANCES_REQUEST";
export const GROUP_BALANCES_SUCCESS="GROUP_BALANCES_SUCCESS";
export const GROUP_BALANCES_FAIL="GROUP_BALANCES_FAIL";

export const UPDATE_GROUP_REQUEST="UPDATE_GROUP_REQUEST";
export const UPDATE_GROUP_SUCCESS="UPDATE_GROUP_SUCCESS";
export const UPDATE_GROUP_FAIL="UPDATE_GROUP_FAIL";
export const UPDATE_GROUP_RESET="UPDATE_GROUP_RESET";

export const ADD_MEMBER_REQUEST="ADD_MEMBER_REQUEST";
export const ADD_MEMBER_SUCCESS="ADD_MEMBER_SUCCESS";
export const ADD_MEMBER_FAIL="ADD_MEMBER_FAIL";
export const ADD_MEMBER_RESET="ADD_MEMBER_RESET";

export const DELETE_MEMBER_REQUEST="DELETE_MEMBER_REQUEST";
export const DELETE_MEMBER_SUCCESS="DELETE_MEMBER_SUCCESS";
export const DELETE_MEMBER_FAIL="DELETE_MEMBER_FAIL";
export const DELETE_MEMBER_RESET="DELETE_MEMBER_RESET";

export const GROUP_USERS_REQUEST="GROUP_USERS_REQUEST";
export const GROUP_USERS_SUCCESS="GROUP_USERS_SUCCESS";
export const GROUP_USERS_FAIL="GROUP_USERS_FAIL";

export const SETTLE_BALANCE_REQUEST="SETTLE_BALANCE_REQUEST";
export const SETTLE_BALANCE_SUCCESS="SETTLE_BALANCE_SUCCESS";
export const SETTLE_BALANCE_FAIL="SETTLE_BALANCE_FAIL";
export const SETTLE_BALANCE_RESET="SETTLE_BALANCE_RESET";

export const CLEAR_ERRORS="CLEAR_ERRORS";